### ISSUE TITLE
Is anyboady had a chance to cross-compile it?

### ISSUE THREAD

**Issue by lifeart** [PiMaker/rvc#1]
Looks like https://github.com/microsoft/ShaderConductor in theory, could make it usable for Web

**Comment by PiMaker** [comment]
*No* \*sprays water\*

There are already risc-v emulators on the web, like the one that some of rvc's emulation code is based on: https://takahirox.github.io/riscv-rust/wasm/web/index.html

Going via webgl/webgpu is just adding layers where they don't need to be. That was sarcastic btw, as this entire project fits that description.
